import type { LayoutConfig } from '@/types/layout';

export const DEFAULT_LAYOUT_CONFIG: LayoutConfig = {
  blocks: [
    {
      id: 'block-bio',
      blockType: 'bio',
      title: '个人简介卡 (Bio Card)',
      visible: true,
      colSpan: 2,
      sectionId: 'bio',
    },
    {
      id: 'block-bookmarks',
      blockType: 'bookmarks',
      title: '常用网站入口 (Bookmarks)',
      visible: true,
      colSpan: 1,
      sectionId: 'portal',
    },
    {
      id: 'block-ai-clone',
      blockType: 'ai_clone',
      title: 'AI 分身对话 (AI Clone)',
      visible: true,
      colSpan: 1,
      sectionId: 'portal',
    },
    {
      id: 'block-app-launcher',
      blockType: 'app_launcher',
      title: 'App 快捷启动 (Launcher)',
      visible: true,
      colSpan: 2,
      sectionId: 'portal',
    },
    {
      id: 'block-projects',
      blockType: 'projects',
      title: '核心项目 Showcase (Projects)',
      visible: true,
      colSpan: 2,
      sectionId: 'projects',
    },
    {
      id: 'block-timeline',
      blockType: 'timeline',
      title: '动态时间线 (Milestones Timeline)',
      visible: true,
      colSpan: 2,
      sectionId: 'experience',
    },
    {
      id: 'block-music',
      blockType: 'music',
      title: '音乐收藏卡片 (Music)',
      visible: true,
      colSpan: 1,
      sectionId: 'media',
    },
    {
      id: 'block-movies',
      blockType: 'movies',
      title: '影视海报墙 (Movies)',
      visible: true,
      colSpan: 1,
      sectionId: 'media',
    },
    {
      id: 'block-books',
      blockType: 'books',
      title: '电子书架 (Books)',
      visible: true,
      colSpan: 1,
      sectionId: 'media',
    },
    {
      id: 'block-friend-links',
      blockType: 'friend_links',
      title: '友情链接 (Friend Links)',
      visible: true,
      colSpan: 1,
      sectionId: 'links',
    },
    {
      id: 'block-contact',
      blockType: 'contact',
      title: '联系方式与社交账号 (Contact)',
      visible: true,
      colSpan: 2,
      sectionId: 'contact',
    },
  ],
  navSections: [
    { id: 'bio', label: '关于我', targetBlockId: 'block-bio' },
    { id: 'portal', label: '快捷入口', targetBlockId: 'block-bookmarks' },
    { id: 'projects', label: '核心项目', targetBlockId: 'block-projects' },
    { id: 'experience', label: '时间线', targetBlockId: 'block-timeline' },
    { id: 'media', label: '兴趣与影音', targetBlockId: 'block-music' },
    { id: 'links', label: '友链', targetBlockId: 'block-friend-links' },
    { id: 'contact', label: '联系方式', targetBlockId: 'block-contact' },
  ],
};
