import {
  User,
  Heart,
  Calendar,
  GraduationCap,
  Briefcase,
  Code2,
  Gamepad2,
  Film,
  Disc,
  BookOpen,
  Send,
  MessageSquare,
  Bell,
  Sparkles,
} from 'lucide-react';
import type { EditorSchema } from './SchemaEditorEngine';

export const EDITOR_SCHEMAS: Record<string, EditorSchema> = {
  profile: {
    id: 'profile',
    title: '1. 个人基本信息 (Basic & Meta)',
    description: '配置网站公开显示的姓名、简介、标签、价值观及 SEO 元数据',
    icon: User,
    fields: [
      { key: 'basic.name', label: '姓名 / 昵称', type: 'text', required: true },
      { key: 'basic.current_status', label: '当前状态', type: 'text', placeholder: '如: 正在构建 iNon OS...' },
      { key: 'basic.intro', label: '一句话简介 / Bio', type: 'textarea' },
      { key: 'basic.keywords', label: '关键词 Keywords', type: 'string-list' },
      { key: 'basic.values', label: '价值观 Values', type: 'string-list' },
      { key: 'basic.tags', label: '个人标签 Tags', type: 'string-list' },
      { key: 'meta.title', label: '网页标题 (Meta Title)', type: 'text' },
      { key: 'meta.author', label: '网页作者 (Meta Author)', type: 'text' },
      { key: 'meta.description', label: '网页描述 (Meta Description)', type: 'text' },
    ],
  },

  life: {
    id: 'life',
    title: '2. 生活状态 (Life)',
    description: '管理常驻城市、MBTI、生日星座及日常饮食与生活习惯',
    icon: Heart,
    fields: [
      { key: 'current_city', label: '常驻城市', type: 'text' },
      { key: 'birth_date', label: '出生日期', type: 'text' },
      { key: 'zodiac_sign', label: '星座', type: 'text' },
      { key: 'mbti.life_mbti', label: '生活 MBTI', type: 'text' },
      { key: 'mbti.work_mbti', label: '工作 MBTI', type: 'text' },
      { key: 'habits', label: '日常习惯 Habits', type: 'string-list' },
      { key: 'diet.favorite_food', label: '喜爱美食 Favorite Food', type: 'string-list' },
      { key: 'diet.favorite_drinks', label: '喜爱饮品 Favorite Drinks', type: 'string-list' },
    ],
  },

  experience: {
    id: 'experience',
    title: '3. 个人里程碑 (Timeline)',
    description: '管理公开的时间轴历程事件与城市分布',
    icon: Calendar,
    fields: [
      {
        key: 'experience',
        label: '时间轴里程碑',
        type: 'object-array',
        createItem: () => ({ date: '', city: '', description: '' }),
        getItemTitle: (item) => `${item.date || '时间'} - ${item.city || '城市'}`,
        subFields: [
          { key: 'date', label: '发生日期 / 年月', placeholder: '如: 2023.08' },
          { key: 'city', label: '城市', placeholder: '如: 深圳' },
          { key: 'description', label: '事件描述', type: 'textarea' },
        ],
      },
    ],
  },

  education: {
    id: 'education',
    title: '4. 教育背景 (Education)',
    description: '管理求学经历、院校专业、学术研究及导师',
    icon: GraduationCap,
    fields: [
      { key: 'undergraduate_major', label: '本科专业', type: 'text' },
      { key: 'undergraduate_advisor', label: '本科导师', type: 'text' },
      {
        key: 'schools',
        label: '学校与院校经历',
        type: 'object-array',
        createItem: () => ({ institution: '', degree: '', major: '', start_date: '', end_date: '' }),
        getItemTitle: (item) => `${item.institution || '学校'} - ${item.degree || '学位'}`,
        subFields: [
          { key: 'institution', label: '院校 / 机构', placeholder: '如: 北京大学' },
          { key: 'degree', label: '学位', placeholder: '如: 学士 / 硕士' },
          { key: 'major', label: '专业', placeholder: '如: 计算机科学' },
          { key: 'start_date', label: '入学时间', placeholder: '如: 2020.09' },
          { key: 'end_date', label: '毕业时间', placeholder: '如: 2024.06' },
        ],
      },
    ],
  },

  work: {
    id: 'work',
    title: '5. 职业履历 (Work)',
    description: '管理工作经历、公司职位、职责及产出偏好',
    icon: Briefcase,
    fields: [
      { key: 'current_job', label: '当前职位', type: 'text' },
      { key: 'work_preferences', label: '工作偏好 Preferences', type: 'string-list' },
      {
        key: 'jobs',
        label: '工作及项目经历',
        type: 'object-array',
        createItem: () => ({
          company_name: '',
          position: '',
          position_type: '',
          start_date: '',
          end_date: '',
          products_responsible_for: '',
          job_summary: '',
          work_output: '',
        }),
        getItemTitle: (item) => `${item.company_name || '公司'} - ${item.position || '职位'}`,
        subFields: [
          { key: 'company_name', label: '公司 / 雇主名称' },
          { key: 'position', label: '担任职位' },
          { key: 'position_type', label: '工作类型', placeholder: '如: 全职 / 兼职' },
          { key: 'start_date', label: '入职日期', placeholder: '如: 2022.06' },
          { key: 'end_date', label: '离职日期', placeholder: '如: 2024.03' },
          { key: 'products_responsible_for', label: '负责产品 / 业务' },
          { key: 'job_summary', label: '工作概述', type: 'textarea' },
          { key: 'work_output', label: '工作产出 / 核心成果', type: 'textarea' },
        ],
      },
    ],
  },

  development: {
    id: 'development',
    title: '6. 技术与项目 (Development)',
    description: '管理所掌握的技术栈、核心开源或商业项目、开发工具箱',
    icon: Code2,
    groups: [
      { id: 'skills', label: '技术与专长', fields: ['skills.tech_stack', 'skills.expertise'] },
      { id: 'projects', label: '代表作品', fields: ['projects'] },
      { id: 'tools', label: '开发工具箱', fields: ['dev_tools'] },
    ],
    fields: [
      { key: 'skills.tech_stack', label: '技术栈 Tech Stack', type: 'string-list' },
      { key: 'skills.expertise', label: '专长领域 Expertise', type: 'string-list' },
      {
        key: 'projects',
        label: '代表作项目 Projects',
        type: 'object-array',
        createItem: () => ({
          project_name: '',
          github: '',
          link: '',
          description: '',
          tech_stack: [],
          role: [],
          start_date: '',
          end_date: '',
          report_link: '',
        }),
        getItemTitle: (item) => item.project_name || '项目名称',
        subFields: [
          { key: 'project_name', label: '项目名称' },
          { key: 'github', label: 'GitHub 仓库 URL' },
          { key: 'link', label: '线上演示链接' },
          { key: 'description', label: '项目简述', type: 'textarea' },
          { key: 'start_date', label: '开始年月' },
          { key: 'end_date', label: '结束年月' },
          { key: 'report_link', label: '复盘/研究报告链接' },
        ],
      },
      {
        key: 'dev_tools',
        label: '开发工具箱 Dev Tools',
        type: 'object-array',
        createItem: () => ({ name: '', link: '', comment: '', tags: [] }),
        getItemTitle: (item) => item.name || '工具名称',
        subFields: [
          { key: 'name', label: '工具名称' },
          { key: 'link', label: '工具链接' },
          { key: 'comment', label: '工具评价/评语', type: 'textarea' },
        ],
      },
    ],
  },

  products: {
    id: 'products',
    title: '7. 装备好物 (Products)',
    description: '展示你的日常随身数码装备、主力数码硬件及喜爱品牌',
    icon: Gamepad2,
    groups: [
      { id: 'hardware', label: '主力硬件', fields: ['my_hardware.phone', 'my_hardware.computer', 'my_hardware.tablet', 'my_hardware.smartwatch', 'my_hardware.headphones'] },
      { id: 'products', label: '好物推荐', fields: ['favorite_products'] },
      { id: 'brands', label: '偏爱品牌', fields: ['favorite_brands'] },
    ],
    fields: [
      { key: 'my_hardware.phone', label: '主力手机', type: 'text' },
      { key: 'my_hardware.computer', label: '主力电脑', type: 'text' },
      { key: 'my_hardware.tablet', label: '主力平板', type: 'text' },
      { key: 'my_hardware.smartwatch', label: '智能手表', type: 'text' },
      { key: 'my_hardware.headphones', label: '日常耳机', type: 'string-list' },
      {
        key: 'favorite_products',
        label: '好物推荐 Products',
        type: 'object-array',
        createItem: () => ({ name: '', link: '', intro: '', image_url: '' }),
        getItemTitle: (item) => item.name || '好物名称',
        subFields: [
          { key: 'name', label: '好物名称' },
          { key: 'link', label: '购买/详情链接' },
          { key: 'intro', label: '一句话点评', type: 'textarea' },
          { key: 'image_url', label: '好物图片 URL', type: 'image' },
        ],
      },
      {
        key: 'favorite_brands',
        label: '偏爱品牌 Brands',
        type: 'object-array',
        createItem: () => ({ name: '', link: '', intro: '', image_url: '' }),
        getItemTitle: (item) => item.name || '品牌名称',
        subFields: [
          { key: 'name', label: '品牌名称' },
          { key: 'link', label: '官网链接' },
          { key: 'intro', label: '品牌态度评语', type: 'textarea' },
          { key: 'image_url', label: '品牌图片 URL', type: 'image' },
        ],
      },
    ],
  },

  creation: {
    id: 'creation',
    title: '8. 创意作品 (Creation)',
    description: '管理制作的视频节目、个人文章专栏、公开演讲、座右铭及名言格言',
    icon: Sparkles,
    groups: [
      { id: 'motto_quote', label: '座右铭与名言', fields: ['mottos', 'quotes'] },
      { id: 'media', label: '视频与播客', fields: ['videos'] },
      { id: 'writing', label: '文章与演讲', fields: ['articles', 'speeches'] },
    ],
    fields: [
      { key: 'mottos', label: '座右铭 Mottos', type: 'string-list' },
      { key: 'quotes', label: '喜爱名言 Quotes', type: 'string-list' },
      {
        key: 'videos',
        label: '视频与播客节目 Videos',
        type: 'object-array',
        createItem: () => ({ series: '', title: '', video_link: '', podcast_link: '', image_url: '' }),
        getItemTitle: (item) => item.title || '视频标题',
        subFields: [
          { key: 'title', label: '视频标题' },
          { key: 'series', label: '所属系列/栏目' },
          { key: 'video_link', label: '视频播放链接' },
          { key: 'podcast_link', label: '音频/播客链接' },
          { key: 'image_url', label: '视频封面图片 URL', type: 'image' },
        ],
      },
      {
        key: 'articles',
        label: '文章与专栏 Articles',
        type: 'object-array',
        createItem: () => ({ title: '', link: '', excerpt: '', image_url: '' }),
        getItemTitle: (item) => item.title || '文章标题',
        subFields: [
          { key: 'title', label: '文章标题' },
          { key: 'link', label: '文章阅读链接' },
          { key: 'excerpt', label: '文章摘要', type: 'textarea' },
          { key: 'image_url', label: '文章封面图片 URL', type: 'image' },
        ],
      },
      {
        key: 'speeches',
        label: '公开演讲/展示 Speeches',
        type: 'object-array',
        createItem: () => ({ speech_name: '', link: '', outline_doc: '', presentation_link: '', image_url: '' }),
        getItemTitle: (item) => item.speech_name || '演讲主题',
        subFields: [
          { key: 'speech_name', label: '演讲主题' },
          { key: 'link', label: '回放链接' },
          { key: 'presentation_link', label: '幻灯片 PPT 链接' },
          { key: 'outline_doc', label: '演讲大纲/手稿文档', type: 'textarea' },
          { key: 'image_url', label: '背景封面图片 URL', type: 'image' },
        ],
      },
    ],
  },

  reading: {
    id: 'reading',
    title: '9. 在读书单与作者 (Reading)',
    description: '管理在读书目、推荐书单、作者档案与读书感悟',
    icon: BookOpen,
    fields: [
      {
        key: 'books',
        label: '书籍档案 Books',
        type: 'object-array',
        createItem: () => ({ name: '', author: '', country: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '书名'} — ${item.author || '作者'}`,
        subFields: [
          { key: 'name', label: '书名' },
          { key: 'author', label: '作者' },
          { key: 'country', label: '国家 / 地区' },
          { key: 'link', label: '豆瓣 / 购买链接' },
          { key: 'comment', label: '读书笔记与评语', type: 'textarea' },
          { key: 'image_url', label: '书籍封面 URL', type: 'image' },
        ],
      },
      {
        key: 'authors',
        label: '喜爱作者 Authors',
        type: 'object-array',
        createItem: () => ({ name: '', country: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => item.name || '作者姓名',
        subFields: [
          { key: 'name', label: '作者姓名' },
          { key: 'country', label: '国家 / 地区' },
          { key: 'link', label: '介绍链接' },
          { key: 'comment', label: '评价与推介', type: 'textarea' },
          { key: 'image_url', label: '作者图片 URL', type: 'image' },
        ],
      },
    ],
  },

  films: {
    id: 'films',
    title: '10. 影视海报墙与导演 (Films)',
    description: '管理看过的影片、最爱电影墙、导演档案与影评',
    icon: Film,
    fields: [
      {
        key: 'films',
        label: '电影与剧集 Films',
        type: 'object-array',
        createItem: () => ({ name: '', director: '', country: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '片名'} — 导演: ${item.director || '未知'}`,
        subFields: [
          { key: 'name', label: '影片名称' },
          { key: 'director', label: '导演' },
          { key: 'country', label: '出品国家 / 地区' },
          { key: 'link', label: '豆瓣 / IMDb 链接' },
          { key: 'comment', label: '影评与观影感受', type: 'textarea' },
          { key: 'image_url', label: '影片封面 URL', type: 'image' },
        ],
      },
      {
        key: 'directors',
        label: '喜爱导演 Directors',
        type: 'object-array',
        createItem: () => ({ name: '', country: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => item.name || '导演姓名',
        subFields: [
          { key: 'name', label: '导演姓名' },
          { key: 'country', label: '国家 / 地区' },
          { key: 'link', label: '介绍链接' },
          { key: 'comment', label: '评价与推介', type: 'textarea' },
          { key: 'image_url', label: '导演图片 URL', type: 'image' },
        ],
      },
    ],
  },

  music: {
    id: 'music',
    title: '11. 喜爱音乐 (Music)',
    description: '管理常听的单曲、最爱专辑墙及喜爱音乐人',
    icon: Disc,
    fields: [
      {
        key: 'albums',
        label: '音乐专辑 Albums',
        type: 'object-array',
        createItem: () => ({ name: '', artist: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '专辑名'} — ${item.artist || '艺人'}`,
        subFields: [
          { key: 'name', label: '专辑名称' },
          { key: 'artist', label: '艺人 / 乐队' },
          { key: 'link', label: '流媒体播放链接' },
          { key: 'comment', label: '专辑乐评', type: 'textarea' },
          { key: 'image_url', label: '专辑封面 URL', type: 'image' },
        ],
      },
      {
        key: 'songs',
        label: '喜爱单曲 Songs',
        type: 'object-array',
        createItem: () => ({ name: '', artist: '', album: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '单曲名'} — ${item.artist || '艺人'}`,
        subFields: [
          { key: 'name', label: '歌曲名称' },
          { key: 'artist', label: '艺人 / 歌手' },
          { key: 'album', label: '所属专辑' },
          { key: 'link', label: '单曲播放链接' },
          { key: 'comment', label: '听歌感悟评语', type: 'textarea' },
          { key: 'image_url', label: '歌曲封面 URL', type: 'image' },
        ],
      },
      {
        key: 'musicians',
        label: '喜爱音乐人 Musicians',
        type: 'object-array',
        createItem: () => ({ name: '', region: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => item.name || '音乐人姓名',
        subFields: [
          { key: 'name', label: '音乐人 / 乐手' },
          { key: 'region', label: '地区 / 风格' },
          { key: 'link', label: '主页介绍链接' },
          { key: 'comment', label: '推介评语', type: 'textarea' },
          { key: 'image_url', label: '艺人照片 URL', type: 'image' },
        ],
      },
    ],
  },

  hiphop: {
    id: 'hiphop',
    title: '11b. 说唱说唱 (Hip Hop)',
    description: '管理 Hip Hop 单曲、最爱说唱专辑墙及说唱艺人',
    icon: Disc,
    fields: [
      {
        key: 'albums',
        label: '说唱专辑 Albums',
        type: 'object-array',
        createItem: () => ({ name: '', artist: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '专辑名'} — ${item.artist || '歌手'}`,
        subFields: [
          { key: 'name', label: '专辑名称' },
          { key: 'artist', label: '歌手' },
          { key: 'link', label: '流媒体播放链接' },
          { key: 'comment', label: '专辑点评', type: 'textarea' },
          { key: 'image_url', label: '专辑封面 URL', type: 'image' },
        ],
      },
      {
        key: 'songs',
        label: '说唱单曲 Songs',
        type: 'object-array',
        createItem: () => ({ name: '', artist: '', album: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => `${item.name || '歌名'} — ${item.artist || '歌手'}`,
        subFields: [
          { key: 'name', label: '歌曲名称' },
          { key: 'artist', label: '说唱歌手' },
          { key: 'album', label: '所属专辑' },
          { key: 'link', label: '播放链接' },
          { key: 'comment', label: '单曲点评', type: 'textarea' },
          { key: 'image_url', label: '单曲封面 URL', type: 'image' },
        ],
      },
      {
        key: 'musicians',
        label: '说唱音乐人 Musicians',
        type: 'object-array',
        createItem: () => ({ name: '', region: '', link: '', comment: '', image_url: '' }),
        getItemTitle: (item) => item.name || '歌手姓名',
        subFields: [
          { key: 'name', label: '说唱艺人' },
          { key: 'region', label: '地区 / 厂牌' },
          { key: 'link', label: '介绍链接' },
          { key: 'comment', label: '推介评语', type: 'textarea' },
          { key: 'image_url', label: '歌手照片 URL', type: 'image' },
        ],
      },
    ],
  },

  events: {
    id: 'events',
    title: '12. 演出演出 (Events)',
    description: '管理公开演出的现场记录及大事件',
    icon: Calendar,
    fields: [
      {
        key: 'performances',
        label: '公开演出活动',
        type: 'object-array',
        createItem: () => ({ type: '', name: '', date: '', genre: '', location: '' }),
        getItemTitle: (item) => `${item.date || '时间'} - ${item.name || '活动名称'}`,
        subFields: [
          { key: 'type', label: '活动类型', placeholder: '如: 演唱会 / 音乐节 / 话剧' },
          { key: 'name', label: '活动 / 演出名称' },
          { key: 'date', label: '演出日期', placeholder: '如: 2024.05.18' },
          { key: 'genre', label: '风格 / 流派' },
          { key: 'location', label: '演出地点 / 场馆' },
        ],
      },
    ],
  },

  contact: {
    id: 'contact',
    title: '13. 联络信息 (Contact)',
    description: '配置日常联络方式（微信、邮箱）以及社交平台/社区的个人主页',
    icon: Send,
    fields: [
      {
        key: 'contact_info',
        label: '主要联系通道',
        type: 'object-array',
        createItem: () => ({ method_name: '', content: '' }),
        getItemTitle: (item) => `${item.method_name || '联系方式'}: ${item.content || ''}`,
        subFields: [
          { key: 'method_name', label: '通道名称', placeholder: '如: WeChat / Email' },
          { key: 'content', label: '联络账号 / 内容', placeholder: '如: jackson@domain.com' },
        ],
      },
      {
        key: 'platform_accounts',
        label: '社交与技术社区平台',
        type: 'object-array',
        createItem: () => ({ platform_name: '', username: '', homepage_link: '' }),
        getItemTitle: (item) => `${item.platform_name || '平台'}: ${item.username || ''}`,
        subFields: [
          { key: 'platform_name', label: '平台名称', placeholder: '如: GitHub / Juejin' },
          { key: 'username', label: '平台用户 ID / 昵称' },
          { key: 'homepage_link', label: '个人主页 URL' },
        ],
      },
    ],
  },

  thoughts: {
    id: 'thoughts',
    title: '14. 个人思想 (Thoughts)',
    description: '记录关于技术、生活、世界的思想切片以及常见的问答记录',
    icon: MessageSquare,
    groups: [
      { id: 'philosophy', label: '个人与行业哲学', fields: ['personal_philosophy', 'industry_views', 'ideology'] },
      { id: 'vision', label: '人生要素与愿景', fields: ['life_elements', 'macro_vision', 'personal_vision'] },
      { id: 'qa', label: '常见 Q&A', fields: ['qa'] },
    ],
    fields: [
      { key: 'personal_philosophy', label: '技术与个人哲学 Philosophy', type: 'string-list' },
      { key: 'industry_views', label: '行业观点 Industry Views', type: 'string-list' },
      { key: 'ideology', label: '思想钢印 Ideology', type: 'string-list' },
      { key: 'life_elements', label: '生活基本要素 Life Elements', type: 'string-list' },
      { key: 'macro_vision', label: '宏观愿景 Macro Vision', type: 'string-list' },
      { key: 'personal_vision', label: '个人微观愿景 Personal Vision', type: 'string-list' },
      {
        key: 'qa',
        label: '常见问题解答 (Q&A)',
        type: 'object-array',
        createItem: () => ({ question: '', answer: '', source: '', date: '' }),
        getItemTitle: (item) => item.question || '问题',
        subFields: [
          { key: 'question', label: '问题 Question' },
          { key: 'answer', label: '回答 Answer', type: 'textarea' },
          { key: 'source', label: '来源 / 出处' },
          { key: 'date', label: '记录年月' },
        ],
      },
    ],
  },

  notifications: {
    id: 'notifications',
    title: '15. 公告动态 (Notifications)',
    description: '管理公开主页顶部滚动的置顶动态、公告与近期广播',
    icon: Bell,
    fields: [
      {
        key: 'notifications',
        label: '公告栏置顶动态',
        type: 'object-array',
        createItem: () => ({ date: '', text: '', type: '' }),
        getItemTitle: (item) => `${item.date || '日期'}: ${item.text || ''}`,
        subFields: [
          { key: 'date', label: '公告日期', placeholder: '如: 2024.06.01' },
          { key: 'text', label: '公告动态文字内容', type: 'textarea' },
          { key: 'type', label: '分类 / 等级', placeholder: '如: info / warning / success' },
        ],
      },
    ],
  },
};
